# These are supported funding model platforms

github: mjpt1
# Uncomment and set when you create accounts:
# buy_me_a_coffee: your-username
# ko_fi: your-username
# open_collective: your-collective
# custom:
#   - "https://example.com/support"
